### ISSUE TITLE
Deposits (messages) from PolygonZKEvm to L1 are stuck

### ISSUE THREAD

**Issue by GabrielBuragev** [0xPolygonHermez/zkevm-bridge-service#450]
While trying to integrate PolygonZKEvm in our local E2E tests at Beamer Bridge, we noticed an inconsistent behavior between the different runs of it (tests are flaky).
We've seen that sometimes we end up with successful relays and sometimes not.

We are using your `zkevm-bridge-service` repository to spin up a local PolygonZKEvm environment.

How our E2E testing flow looks likes:
1. Initialize/bring up the local (dockerized) PolygonZKEvm environment - https://github.com/beamer-bridge/beamer/blob/main/docker/polygon_zkevm/polygon_zkevm.sh#L109-L111
2. Deploy Beamer protocol on PolygonZKEvm & Geth L1 - https://github.com/beamer-bridge/beamer/blob/main/docker/polygon_zkevm/polygon_zkevm.sh#L117-L120
3. Run the E2E test (https://github.com/beamer-bridge/beamer/blob/main/docker/polygon_zkevm/polygon_zkevm.sh#L122-L124) which:
- Sends a message from L2 to L1 by submitting a call to [this contract function](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/FillManager.sol) after [creating a transfer request](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/RequestManager.sol#L338-L418). 
The `fillRequest` call will send a message to [our own PolygonZKEvm messengers](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/chains/polygon_zkevm/PolygonZkEVMMessengers.sol) on L2 which will forward this message to the `PolygonZKEvmBridge` (on L2) by calling `PolygonZkEVMBridge.bridgeMessage(...)`
- Call our relayer which [waits for the message to be ready for claiming (relaying)](https://github.com/beamer-bridge/beamer/blob/main/relayer/src/services/relayer/polygon-zkevm.ts#L114-L194) after which it relays it (by calling `PolygonZkEVMBridge.claimMessage`) on L1
- Verify that the message arrived at the destination by scanning certain contract events (step not relevant for this bug report)

In order to reproduce the problem we are experiencing, one needs to:
- Clone our repository - `git clone --recurse-submodules https://github.com/beamer-bridge/beamer.git`
- Enter the beamer folder - `cd beamer`
- Checkout this branch - `git checkout polygon-zkevm-e2e-debug`
- Make the relayer binaries - `make relayers`
- Start up the local PolygonZKEvm environment - `./docker/polygon_zkevm/polygon_zkevm.sh up`
- Run `docker logs -f zkevm_node | grep ERROR` in one terminal. You will use this terminal to detect when the problem appears.
- Open another terminal and deploy beamer - `./docker/polygon_zkevm/polygon_zkevm.sh deploy-beamer`
- After contracts have been deployed, run the E2E tests by running `./docker/polygon_zkevm/polygon_zkevm.sh e2e-test` until the ERROR logs show up (this might mean that you need to run the `e2e-test` command multiple times until the logs appear). They should look something like:
```
2023-06-19T15:51:55.494Z        ERROR   ethtxmanager/ethtxmanager.go:392        failed to send tx 0x21acf28535683372310c4c20d047d297133b1e974a24a831de26ee09d55a234c to network: replacement transaction underpriced    {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-18-to-18"}
2023-06-19T15:51:56.501Z        ERROR   ethtxmanager/ethtxmanager.go:392        failed to send tx 0x21acf28535683372310c4c20d047d297133b1e974a24a831de26ee09d55a234c to network: nonce too low  {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-18-to-18"}
2023-06-19T15:51:57.507Z        ERROR   ethtxmanager/ethtxmanager.go:392        failed to send tx 0x21acf28535683372310c4c20d047d297133b1e974a24a831de26ee09d55a234c to network: nonce too low  {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-18-to-18"}
```

Note: **Make sure you run all the above commands from the root of the project, otherwise they might not work.**

Once you start seeing the ERROR logs in the terminal, the state will stop synchronizing between L2 and L1 (future deposits/messages will never arrive/be included on L1) and therefore our e2e tests will hang forever at this log line: 
`Waiting for message to be ready for claiming.`

We already tested the same process on testnet (Goerli) and it was not possible to reproduce it there.

**This problem is present both with the latest version of your `develop` branch and at this commit: https://github.com/0xPolygonHermez/zkevm-bridge-service/tree/09e0247b335a19a5e16945e8e1e805e410e41ca3 (which is used on our `main` branch)**

**Comment by ARR552** [comment]
Hello @GabrielBuragev 
I've tried to run the environment but I couldn't. Firstly, I had to install yarn for the make relayers command. The make command ended with the next logs:
```
prebuild-install warn install connect ECONNREFUSED 127.0.0.1:80
prebuild-install warn install connect ECONNREFUSED 127.0.0.1:80
> Warning Failed to make bytecode node18-x64 for file /snapshot/relayer/node_modules/rustbn.js/lib/index.asm.js
Done in 39.78s.
mkdir -p beamer/data/relayers
cp relayer/relayer-*-x64 beamer/data/relayers
```
After this I tried to run  `./docker/polygon_zkevm/polygon_zkevm.sh up` with the next output.
```
./beamer/docker/polygon_zkevm/../scripts/common.sh: line 30: poetry: order not found
```
From that point I couldn't run anything else.

However, the problem seems to be that you are using the same account in different services  and txs are being overlapped. Please review that you are using different accounts for each component in the node and the bridge.

**Comment by istankovic** [comment]
Hey @ARR552, thanks for helping us investigate this!

In order to reproduce this on your end, you would also need Python poetry and it would be best to initialize the environment before starting the containers, like so:
```
(in the root  of our repo)
$ poetry shell
$ poetry install
$ ./docker/polygon_zkevm/polygon_zkevm.sh up
```


> However, the problem seems to be that you are using the same account in different services and txs are being overlapped

I am not sure what you mean by this, because we are not setting accounts for polygon docker services.
@GabrielBuragev, please correct me if I'm wrong.

**Comment by GabrielBuragev** [comment]
Hi @ARR552, thanks for the response!
Sorry, i forgot to write the step for installing the deps.

Can you try running 
- `poetry install`
- `poetry shell`

from the root folder of the project before trying to run all the other steps related to the e2e test?
For this you will need to have Python poetry installed locally.

Btw, i just checked and we are not setting any accounts in the docker services. We only ever call the `zkevm-node` via RPC calls in a way that we submit a couple of transactions one after another. Whatever happens underneath (in the node's code), apparently messes up with the original nonces of our transactions to a point where they are invalid? 

Is it possible that we are sending the transactions too fast? Do we need to first wait for a transaction to be mined first before submitting a new one or?

I also noticed that the problem sometimes occurs in the deployment step (`./docker/polygon_zkevm/polygon_zkevm.sh deploy-beamer`) which is before the e2e-test step (`./docker/polygon_zkevm/polygon_zkevm.sh e2e-test`).
Since for the deployment we are using one script and one provider instance, the nonce should not get messed up right? 
I do however understand that when you use the same account in different components, nonces can get messed up. But how is it then possible that it happens in the deployment step? 😕

**Comment by GabrielBuragev** [comment]
I will try to debug the nonces that we are sending on our end and see if they somehow get messed up on our end.

**Comment by sahil3Vedi** [comment]
Hi @GabrielBuragev regarding the 'nonce too low' error you may refer this (guide)[https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Clear_Pending_Transactions.md] on how to mitigate it. It involves sending a 0ETH transaction to one's own account and manually assigning the appropriate nonce to the transaction. You can run the `ethersjs` script by mentioning your `RPC`, `sender's address` and `private key` inside the script.

Let me know if it works!

**Comment by fredo** [comment]
I would like to emphasize again, that we assume that the nonce too low issue does *not* occur from our transactions but appearantly from internal transactions (sequencer or prover writing to L1). 

As @GabrielBuragev pointed out, we only see successful transactions being send in our logs. The tx hashes of the shown errors of the zknode display a tx hash which cannot be found in our logs (so we assume this tx is not sent by us rather by the internal nodes like the sequencer or prover). 

Additionally, what brings us to the belief that it could be internal transactions which cause this problem, we see in the error logs either ` "monitoredTx": "proof-from-8-to-8"` or `"monitoredTx": "sequence-from-18-to-18"`

**Comment by compojoom** [comment]
@ARR552 you should do

```
poetry shell
```

which will create a virtual environment and afterwards you have to run:
```
poetry install
```

After that running the up command should work.

**Comment by ARR552** [comment]
The problem as I commented previously is that you are using the same accounts of the ethtxmanager for running your scripts.
```
ADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
```
This account shouldn't be use because it is used by the node in L1 for the ethtxmanager and used by the bridge in L2 to do the autoclaims in the local test environment.

The piece of code where i see that you use this account is:
``
    account = account_from_keyfile(keystore_file, password)
    print("Deployer:", account.address)

    web3_l1 = make_web3(config.base_chain.rpc, account, _margin_gas_price_strategy)

    resolver = deploy_contract(web3_l1, "Resolver")
```
this print is shown in this log:
```
Deployer: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
```

So, you can not use the next accounts to deploy contracts or do stuff in your test because they are already being used for the node and bridge.
```
0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
0x70997970C51812dc3A010C7d01b50e0d17dc79C8
```

You have two options. Modify these accounts in the zkevm-node and zkevm-bridge (I don't recommend it) or change the account in the script deployment and others.

**Comment by ARR552** [comment]
@fredo  the doc is outdated in this case. Thank you for reporting, we'll fix it assap

**Comment by compojoom** [comment]
@ARR552 yes, you are right! The problem comes from the fact that we are using `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266` . I guess it is a documentation issue. 
We needed an account that has funds on l2, but the only such account was the `f3...` address. 
We tried to fund a different account by submitting a transfer on l2 from `f3...` to a different account, but that was also screwing the nonces. 

Yesterday evening I found out that you have a script to deposit funds: https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/develop/test/scripts/deposit/main.go

I had to modify it to send to a different account, but with that change it works. 

Btw, we also needed funds on L1, so we went with the first account from here:
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/running_local.md#accounts

The problem it turns out is that `0x70997970C51812dc3A010C7d01b50e0d17dc79C8` is the aggregator account - so when I used it we again ran into the "nonce too low" issue. This has to be documented in the node repo.


I created a PR with info on how to fund an account on L2: https://github.com/0xPolygonHermez/zkevm-bridge-service/pull/455

**Comment by ARR552** [comment]
This accounts should be used only for testing purposes. Both have funds in L1
```
Account Address:  0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC
PrivKey:  0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
Account Address:  0x90F79bf6EB2c4f870365E785982E1f101E93b906
PrivKey:  0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
```
You can just use one of these accounts and use the deposit script to bridge funds

**Comment by ARR552** [comment]
Another option, could be send L2 funds from `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266` to another account before running the bridge service. But must be done before running the bridge, if not you can have problems on the autoclaim. This won't affect L1 interaction because the nonces are different. When you run the bridge, It will check the nonce of the account and will realize that is 1 instead of 0.

**Comment by compojoom** [comment]
Yes, I went for 0x3C4...
https://github.com/beamer-bridge/beamer/pull/1976/files

and maybe we can parametrize the deposit script, so that we don't have to use sed to override it?
